
package com.uspring.sdsmesplus.wms.sap.f080;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_EMS2EWM_PPOrdersHours_Async_OutService", targetNamespace = "urn:mes:PPOrderHours", wsdlLocation = "file:/D:/\u62a5\u5de5SI_EMS2EWM_PPOrdersHours_Async_OutService.wsdl")
public class SIEMS2EWMPPOrdersHoursAsyncOutService
    extends Service
{

    private final static URL SIEMS2EWMPPORDERSHOURSASYNCOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIEMS2EWMPPORDERSHOURSASYNCOUTSERVICE_EXCEPTION;
    private final static QName SIEMS2EWMPPORDERSHOURSASYNCOUTSERVICE_QNAME = new QName("urn:mes:PPOrderHours", "SI_EMS2EWM_PPOrdersHours_Async_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/\u62a5\u5de5SI_EMS2EWM_PPOrdersHours_Async_OutService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIEMS2EWMPPORDERSHOURSASYNCOUTSERVICE_WSDL_LOCATION = url;
        SIEMS2EWMPPORDERSHOURSASYNCOUTSERVICE_EXCEPTION = e;
    }

    public SIEMS2EWMPPOrdersHoursAsyncOutService() {
        super(__getWsdlLocation(), SIEMS2EWMPPORDERSHOURSASYNCOUTSERVICE_QNAME);
    }

    public SIEMS2EWMPPOrdersHoursAsyncOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIEMS2EWMPPORDERSHOURSASYNCOUTSERVICE_QNAME, features);
    }

    public SIEMS2EWMPPOrdersHoursAsyncOutService(URL wsdlLocation) {
        super(wsdlLocation, SIEMS2EWMPPORDERSHOURSASYNCOUTSERVICE_QNAME);
    }

    public SIEMS2EWMPPOrdersHoursAsyncOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIEMS2EWMPPORDERSHOURSASYNCOUTSERVICE_QNAME, features);
    }

    public SIEMS2EWMPPOrdersHoursAsyncOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIEMS2EWMPPOrdersHoursAsyncOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIEMS2EWMPPOrdersHoursAsyncOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIEMS2EWMPPOrdersHoursAsyncOut getHTTPPort() {
        return super.getPort(new QName("urn:mes:PPOrderHours", "HTTP_Port"), SIEMS2EWMPPOrdersHoursAsyncOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIEMS2EWMPPOrdersHoursAsyncOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIEMS2EWMPPOrdersHoursAsyncOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:PPOrderHours", "HTTP_Port"), SIEMS2EWMPPOrdersHoursAsyncOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIEMS2EWMPPOrdersHoursAsyncOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIEMS2EWMPPOrdersHoursAsyncOut getHTTPSPort() {
        return super.getPort(new QName("urn:mes:PPOrderHours", "HTTPS_Port"), SIEMS2EWMPPOrdersHoursAsyncOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIEMS2EWMPPOrdersHoursAsyncOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIEMS2EWMPPOrdersHoursAsyncOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:PPOrderHours", "HTTPS_Port"), SIEMS2EWMPPOrdersHoursAsyncOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIEMS2EWMPPORDERSHOURSASYNCOUTSERVICE_EXCEPTION!= null) {
            throw SIEMS2EWMPPORDERSHOURSASYNCOUTSERVICE_EXCEPTION;
        }
        return SIEMS2EWMPPORDERSHOURSASYNCOUTSERVICE_WSDL_LOCATION;
    }

}
