
package com.uspring.sdsmesplus.wms.sap.f080;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_EMS2EWM_PPOrdersHours_Async_Out", targetNamespace = "urn:mes:PPOrderHours")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIEMS2EWMPPOrdersHoursAsyncOut {


    /**
     * 
     * @param mtZPPCNFM1
     */
    @WebMethod(operationName = "SI_EMS2EWM_PPOrdersHours_Async_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @Oneway
    public void siEMS2EWMPPOrdersHoursAsyncOut(
        @WebParam(name = "MT_ZPPCNFM1", targetNamespace = "urn:mes:PPOrderHours", partName = "MT_ZPPCNFM1")
        DTZSEAFKOES mtZPPCNFM1);

}
