
package com.uspring.sdsmesplus.wms.sap.f080;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_SRM_CreCharge_Out", targetNamespace = "urn:srm:CreCharg")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SISRMCreChargeOut {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.uspring.sdsmesplus.wms.sap.f080.ZMMICREATECHARGResponse
     */
    @WebMethod(operationName = "SI_SRM_CreCharge_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ZMMI_CREATE_CHARG.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    public ZMMICREATECHARGResponse siSRMCreChargeOut(
        @WebParam(name = "ZMMI_CREATE_CHARG", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
        ZMMICREATECHARG parameters);

}
