
package com.uspring.sdsmesplus.wms.sap.f080;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_SRM_CreCharge_OutService", targetNamespace = "urn:srm:CreCharg", wsdlLocation = "http://10.50.52.152:10005/F080-SI_SRM_CreCharge_OutService.wsdl")
public class SISRMCreChargeOutService
    extends Service
{

    private final static URL SISRMCRECHARGEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SISRMCRECHARGEOUTSERVICE_EXCEPTION;
    private final static QName SISRMCRECHARGEOUTSERVICE_QNAME = new QName("urn:srm:CreCharg", "SI_SRM_CreCharge_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.52.152:10005/F080-SI_SRM_CreCharge_OutService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SISRMCRECHARGEOUTSERVICE_WSDL_LOCATION = url;
        SISRMCRECHARGEOUTSERVICE_EXCEPTION = e;
    }

    public SISRMCreChargeOutService() {
        super(__getWsdlLocation(), SISRMCRECHARGEOUTSERVICE_QNAME);
    }

    public SISRMCreChargeOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SISRMCRECHARGEOUTSERVICE_QNAME, features);
    }

    public SISRMCreChargeOutService(URL wsdlLocation) {
        super(wsdlLocation, SISRMCRECHARGEOUTSERVICE_QNAME);
    }

    public SISRMCreChargeOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SISRMCRECHARGEOUTSERVICE_QNAME, features);
    }

    public SISRMCreChargeOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SISRMCreChargeOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SISRMCreChargeOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISRMCreChargeOut getHTTPPort() {
        return super.getPort(new QName("urn:srm:CreCharg", "HTTP_Port"), SISRMCreChargeOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISRMCreChargeOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISRMCreChargeOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:srm:CreCharg", "HTTP_Port"), SISRMCreChargeOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SISRMCreChargeOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISRMCreChargeOut getHTTPSPort() {
        return super.getPort(new QName("urn:srm:CreCharg", "HTTPS_Port"), SISRMCreChargeOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISRMCreChargeOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISRMCreChargeOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:srm:CreCharg", "HTTPS_Port"), SISRMCreChargeOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SISRMCRECHARGEOUTSERVICE_EXCEPTION!= null) {
            throw SISRMCRECHARGEOUTSERVICE_EXCEPTION;
        }
        return SISRMCRECHARGEOUTSERVICE_WSDL_LOCATION;
    }

}
