
package com.uspring.sdsmesplus.wms.sap.f135;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_MES_STOCKDETAIL_Out", targetNamespace = "urn:mes:f135:GetStockDetails",
        serviceName="SI_MES_STOCKDETAIL_OutService", portName="HTTP_Port")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIMESSTOCKDETAILOut {


    /**
     * 
     * @param mtMESSTOCKDETAIL
     * @return
     *     returns com.uspring.sdsmesplus.wms.sap.f135.DTMESSTOCKDETAILRSP
     */
    @WebMethod(operationName = "SI_MES_STOCKDETAIL_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_MES_STOCKDETAIL_RSP", targetNamespace = "urn:mes:f135:GetStockDetails", partName = "MT_MES_STOCKDETAIL_RSP")
    public DTMESSTOCKDETAILRSP siMESSTOCKDETAILOut(
            @WebParam(name = "MT_MES_STOCKDETAIL", targetNamespace = "urn:mes:f135:GetStockDetails", partName = "MT_MES_STOCKDETAIL")
                    DTMESSTOCKDETAIL mtMESSTOCKDETAIL);

}
