
package com.uspring.sdsmesplus.wms.sap.f135;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MES_STOCKDETAIL_OutService", targetNamespace = "urn:mes:f135:GetStockDetails",
        wsdlLocation = "http://10.50.52.152:10005/F135_DEV_SI_MES_STOCKDETAIL_OutService.wsdl")
public class SIMESSTOCKDETAILOutService
    extends Service
{

    private final static URL SIMESSTOCKDETAILOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMESSTOCKDETAILOUTSERVICE_EXCEPTION;
    private final static QName SIMESSTOCKDETAILOUTSERVICE_QNAME = new QName("urn:mes:f135:GetStockDetails", "SI_MES_STOCKDETAIL_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.52.152:10005/F135_DEV_SI_MES_STOCKDETAIL_OutService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMESSTOCKDETAILOUTSERVICE_WSDL_LOCATION = url;
        SIMESSTOCKDETAILOUTSERVICE_EXCEPTION = e;
    }

    public SIMESSTOCKDETAILOutService() {
        super(__getWsdlLocation(), SIMESSTOCKDETAILOUTSERVICE_QNAME);
    }

    public SIMESSTOCKDETAILOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMESSTOCKDETAILOUTSERVICE_QNAME, features);
    }

    public SIMESSTOCKDETAILOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMESSTOCKDETAILOUTSERVICE_QNAME);
    }

    public SIMESSTOCKDETAILOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMESSTOCKDETAILOUTSERVICE_QNAME, features);
    }

    public SIMESSTOCKDETAILOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMESSTOCKDETAILOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMESSTOCKDETAILOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESSTOCKDETAILOut getHTTPPort() {
        return super.getPort(new QName("urn:mes:f135:GetStockDetails", "HTTP_Port"), SIMESSTOCKDETAILOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESSTOCKDETAILOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESSTOCKDETAILOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:f135:GetStockDetails", "HTTP_Port"), SIMESSTOCKDETAILOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMESSTOCKDETAILOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESSTOCKDETAILOut getHTTPSPort() {
        return super.getPort(new QName("urn:mes:f135:GetStockDetails", "HTTPS_Port"), SIMESSTOCKDETAILOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESSTOCKDETAILOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESSTOCKDETAILOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:f135:GetStockDetails", "HTTPS_Port"), SIMESSTOCKDETAILOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMESSTOCKDETAILOUTSERVICE_EXCEPTION!= null) {
            throw SIMESSTOCKDETAILOUTSERVICE_EXCEPTION;
        }
        return SIMESSTOCKDETAILOUTSERVICE_WSDL_LOCATION;
    }

}
