
package com.uspring.sdsmesplus.wms.sap.f113;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MES_JudgeSafeLaunch_OutService", targetNamespace = "urn:mes:f113:JudgeSafeLaunch", wsdlLocation = "http://10.50.52.152:10005/F113_QAS_SI_MES_JudgeSafeLaunch_OutService.wsdl")
public class SIMESJudgeSafeLaunchOutService
    extends Service
{

    private final static URL SIMESJUDGESAFELAUNCHOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMESJUDGESAFELAUNCHOUTSERVICE_EXCEPTION;
    private final static QName SIMESJUDGESAFELAUNCHOUTSERVICE_QNAME = new QName("urn:mes:f113:JudgeSafeLaunch", "SI_MES_JudgeSafeLaunch_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.52.152:10005/F113_QAS_SI_MES_JudgeSafeLaunch_OutService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMESJUDGESAFELAUNCHOUTSERVICE_WSDL_LOCATION = url;
        SIMESJUDGESAFELAUNCHOUTSERVICE_EXCEPTION = e;
    }

    public SIMESJudgeSafeLaunchOutService() {
        super(__getWsdlLocation(), SIMESJUDGESAFELAUNCHOUTSERVICE_QNAME);
    }

    public SIMESJudgeSafeLaunchOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMESJUDGESAFELAUNCHOUTSERVICE_QNAME, features);
    }

    public SIMESJudgeSafeLaunchOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMESJUDGESAFELAUNCHOUTSERVICE_QNAME);
    }

    public SIMESJudgeSafeLaunchOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMESJUDGESAFELAUNCHOUTSERVICE_QNAME, features);
    }

    public SIMESJudgeSafeLaunchOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMESJudgeSafeLaunchOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMESJudgeSafeLaunchOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESJudgeSafeLaunchOut getHTTPPort() {
        return super.getPort(new QName("urn:mes:f113:JudgeSafeLaunch", "HTTP_Port"), SIMESJudgeSafeLaunchOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESJudgeSafeLaunchOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESJudgeSafeLaunchOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:f113:JudgeSafeLaunch", "HTTP_Port"), SIMESJudgeSafeLaunchOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMESJudgeSafeLaunchOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESJudgeSafeLaunchOut getHTTPSPort() {
        return super.getPort(new QName("urn:mes:f113:JudgeSafeLaunch", "HTTPS_Port"), SIMESJudgeSafeLaunchOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESJudgeSafeLaunchOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESJudgeSafeLaunchOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:f113:JudgeSafeLaunch", "HTTPS_Port"), SIMESJudgeSafeLaunchOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMESJUDGESAFELAUNCHOUTSERVICE_EXCEPTION!= null) {
            throw SIMESJUDGESAFELAUNCHOUTSERVICE_EXCEPTION;
        }
        return SIMESJUDGESAFELAUNCHOUTSERVICE_WSDL_LOCATION;
    }

}
