
package com.uspring.sdsmesplus.wms.sap.f113;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_MES_JudgeSafeLaunch_Out", targetNamespace = "urn:mes:f113:JudgeSafeLaunch")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIMESJudgeSafeLaunchOut {


    /**
     * 
     * @param mtSafeLaunch
     * @return
     *     returns com.uspring.sdsmesplus.wms.sap.f113.DTSafeLaunchRT
     */
    @WebMethod(operationName = "SI_MES_JudgeSafeLaunch_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_SafeLaunch_RT", targetNamespace = "urn:mes:f113:JudgeSafeLaunch", partName = "MT_SafeLaunch_RT")
    public DTSafeLaunchRT siMESJudgeSafeLaunchOut(
        @WebParam(name = "MT_SafeLaunch", targetNamespace = "urn:mes:f113:JudgeSafeLaunch", partName = "MT_SafeLaunch")
        DTSafeLaunch mtSafeLaunch);

}
