
package com.uspring.sdsmesplus.wms.sap.f049;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MES_SuspectIsolation_OutService", targetNamespace = "urn:mes:SuspectIsolation", wsdlLocation = "http://10.50.52.152:10005/F049_QAS_SI_MES_SuspectIsolation_OutService.wsdl")
public class SIMESSuspectIsolationOutService
    extends Service
{

    private final static URL SIMESSUSPECTISOLATIONOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMESSUSPECTISOLATIONOUTSERVICE_EXCEPTION;
    private final static QName SIMESSUSPECTISOLATIONOUTSERVICE_QNAME = new QName("urn:mes:SuspectIsolation", "SI_MES_SuspectIsolation_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.52.152:10005/F049_QAS_SI_MES_SuspectIsolation_OutService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMESSUSPECTISOLATIONOUTSERVICE_WSDL_LOCATION = url;
        SIMESSUSPECTISOLATIONOUTSERVICE_EXCEPTION = e;
    }

    public SIMESSuspectIsolationOutService() {
        super(__getWsdlLocation(), SIMESSUSPECTISOLATIONOUTSERVICE_QNAME);
    }

    public SIMESSuspectIsolationOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMESSUSPECTISOLATIONOUTSERVICE_QNAME, features);
    }

    public SIMESSuspectIsolationOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMESSUSPECTISOLATIONOUTSERVICE_QNAME);
    }

    public SIMESSuspectIsolationOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMESSUSPECTISOLATIONOUTSERVICE_QNAME, features);
    }

    public SIMESSuspectIsolationOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMESSuspectIsolationOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMESSuspectIsolationOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESSuspectIsolationOut getHTTPPort() {
        return super.getPort(new QName("urn:mes:SuspectIsolation", "HTTP_Port"), SIMESSuspectIsolationOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESSuspectIsolationOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESSuspectIsolationOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:SuspectIsolation", "HTTP_Port"), SIMESSuspectIsolationOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMESSuspectIsolationOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESSuspectIsolationOut getHTTPSPort() {
        return super.getPort(new QName("urn:mes:SuspectIsolation", "HTTPS_Port"), SIMESSuspectIsolationOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESSuspectIsolationOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESSuspectIsolationOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:SuspectIsolation", "HTTPS_Port"), SIMESSuspectIsolationOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMESSUSPECTISOLATIONOUTSERVICE_EXCEPTION!= null) {
            throw SIMESSUSPECTISOLATIONOUTSERVICE_EXCEPTION;
        }
        return SIMESSUSPECTISOLATIONOUTSERVICE_WSDL_LOCATION;
    }

}
