
package com.uspring.sdsmesplus.wms.sap.f049;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_MES_SuspectIsolation_Out", targetNamespace = "urn:mes:SuspectIsolation")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIMESSuspectIsolationOut {


    /**
     * 
     * @param mtWIPTRANFINPUT
     * @return
     *     returns com.f049.DTWIPTRANFOUTPUT
     */
    @WebMethod(operationName = "SI_MES_SuspectIsolation_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_WIP_TRANF_OUTPUT", targetNamespace = "urn:mes:SuspectIsolation", partName = "MT_WIP_TRANF_OUTPUT")
    public DTWIPTRANFOUTPUT siMESSuspectIsolationOut(
        @WebParam(name = "MT_WIP_TRANF_INPUT", targetNamespace = "urn:mes:SuspectIsolation", partName = "MT_WIP_TRANF_INPUT")
        DTWIPTRANFINPUT mtWIPTRANFINPUT);

}
