
package com.uspring.sdsmesplus.barcode.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BillNoService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.50.52.152:10005/BillNoService.wsdl")
public class BillNoService
    extends Service
{

    private final static URL BILLNOSERVICE_WSDL_LOCATION;
    private final static WebServiceException BILLNOSERVICE_EXCEPTION;
    private final static QName BILLNOSERVICE_QNAME = new QName("http://tempuri.org/", "BillNoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.52.152:10005/BillNoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BILLNOSERVICE_WSDL_LOCATION = url;
        BILLNOSERVICE_EXCEPTION = e;
    }

    public BillNoService() {
        super(__getWsdlLocation(), BILLNOSERVICE_QNAME);
    }

    public BillNoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BILLNOSERVICE_QNAME, features);
    }

    public BillNoService(URL wsdlLocation) {
        super(wsdlLocation, BILLNOSERVICE_QNAME);
    }

    public BillNoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BILLNOSERVICE_QNAME, features);
    }

    public BillNoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillNoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BillNoServiceSoap
     */
    @WebEndpoint(name = "BillNoServiceSoap")
    public BillNoServiceSoap getBillNoServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "BillNoServiceSoap"), BillNoServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillNoServiceSoap
     */
    @WebEndpoint(name = "BillNoServiceSoap")
    public BillNoServiceSoap getBillNoServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BillNoServiceSoap"), BillNoServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BILLNOSERVICE_EXCEPTION!= null) {
            throw BILLNOSERVICE_EXCEPTION;
        }
        return BILLNOSERVICE_WSDL_LOCATION;
    }

}
