
package com.uspring.sdsmesplus.barcode.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MaterialPullService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.50.52.152:10005/MaterialPullService.wsdl")
public class MaterialPullService
    extends Service
{

    private final static URL MATERIALPULLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MATERIALPULLSERVICE_EXCEPTION;
    private final static QName MATERIALPULLSERVICE_QNAME = new QName("http://tempuri.org/", "MaterialPullService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.52.152:10005/MaterialPullService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATERIALPULLSERVICE_WSDL_LOCATION = url;
        MATERIALPULLSERVICE_EXCEPTION = e;
    }

    public MaterialPullService() {
        super(__getWsdlLocation(), MATERIALPULLSERVICE_QNAME);
    }

    public MaterialPullService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATERIALPULLSERVICE_QNAME, features);
    }

    public MaterialPullService(URL wsdlLocation) {
        super(wsdlLocation, MATERIALPULLSERVICE_QNAME);
    }

    public MaterialPullService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATERIALPULLSERVICE_QNAME, features);
    }

    public MaterialPullService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MaterialPullService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MaterialPullServiceSoap
     */
    @WebEndpoint(name = "MaterialPullServiceSoap")
    public MaterialPullServiceSoap getMaterialPullServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "MaterialPullServiceSoap"), MaterialPullServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MaterialPullServiceSoap
     */
    @WebEndpoint(name = "MaterialPullServiceSoap")
    public MaterialPullServiceSoap getMaterialPullServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "MaterialPullServiceSoap"), MaterialPullServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATERIALPULLSERVICE_EXCEPTION!= null) {
            throw MATERIALPULLSERVICE_EXCEPTION;
        }
        return MATERIALPULLSERVICE_WSDL_LOCATION;
    }

}
