
package com.uspring.sdsmesplus.barcode.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PDAWebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PDAWebServiceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getDBCurTime")
    @WebResult(name = "getDBCurTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getDBCurTime", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetDBCurTime")
    @ResponseWrapper(localName = "getDBCurTimeResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetDBCurTimeResponse")
    public String getDBCurTime();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getEffectDateShiftByCurDate")
    @WebResult(name = "getEffectDateShiftByCurDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getEffectDateShiftByCurDate", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetEffectDateShiftByCurDate")
    @ResponseWrapper(localName = "getEffectDateShiftByCurDateResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetEffectDateShiftByCurDateResponse")
    public String getEffectDateShiftByCurDate();

    /**
     * 
     * @param strDomain
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.ArrayOfCSite
     */
    @WebMethod(action = "http://tempuri.org/getSitesByDomain")
    @WebResult(name = "getSitesByDomainResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getSitesByDomain", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetSitesByDomain")
    @ResponseWrapper(localName = "getSitesByDomainResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetSitesByDomainResponse")
    public ArrayOfCSite getSitesByDomain(
        @WebParam(name = "strDomain", targetNamespace = "http://tempuri.org/")
        String strDomain);

    /**
     * 
     * @param strSite
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.ArrayOfCLocation
     */
    @WebMethod(action = "http://tempuri.org/getLocationsBySite")
    @WebResult(name = "getLocationsBySiteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getLocationsBySite", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetLocationsBySite")
    @ResponseWrapper(localName = "getLocationsBySiteResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetLocationsBySiteResponse")
    public ArrayOfCLocation getLocationsBySite(
        @WebParam(name = "strSite", targetNamespace = "http://tempuri.org/")
        String strSite);

    /**
     * 
     * @param strDomain
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.ArrayOfCLocation
     */
    @WebMethod(action = "http://tempuri.org/getLocationsByDomain")
    @WebResult(name = "getLocationsByDomainResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getLocationsByDomain", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetLocationsByDomain")
    @ResponseWrapper(localName = "getLocationsByDomainResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetLocationsByDomainResponse")
    public ArrayOfCLocation getLocationsByDomain(
        @WebParam(name = "strDomain", targetNamespace = "http://tempuri.org/")
        String strDomain);

    /**
     * 
     * @param strDomain
     * @param strToLoc
     * @param loginUser
     * @param strToShelf
     * @param strToSite
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CLocation
     */
    @WebMethod(action = "http://tempuri.org/checkTransferToLoc")
    @WebResult(name = "checkTransferToLocResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "checkTransferToLoc", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.CheckTransferToLoc")
    @ResponseWrapper(localName = "checkTransferToLocResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.CheckTransferToLocResponse")
    public CLocation checkTransferToLoc(
        @WebParam(name = "loginUser", targetNamespace = "http://tempuri.org/")
        CLoginUser loginUser,
        @WebParam(name = "strDomain", targetNamespace = "http://tempuri.org/")
        String strDomain,
        @WebParam(name = "strToLoc", targetNamespace = "http://tempuri.org/")
        String strToLoc,
        @WebParam(name = "strToShelf", targetNamespace = "http://tempuri.org/")
        String strToShelf,
        @WebParam(name = "strToSite", targetNamespace = "http://tempuri.org/")
        String strToSite);

    /**
     * 
     * @param strDomain
     * @param strICCard
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CLocation
     */
    @WebMethod(action = "http://tempuri.org/getLocationByICCard")
    @WebResult(name = "getLocationByICCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getLocationByICCard", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetLocationByICCard")
    @ResponseWrapper(localName = "getLocationByICCardResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetLocationByICCardResponse")
    public CLocation getLocationByICCard(
        @WebParam(name = "strDomain", targetNamespace = "http://tempuri.org/")
        String strDomain,
        @WebParam(name = "strICCard", targetNamespace = "http://tempuri.org/")
        String strICCard);

    /**
     * 
     * @param strDomain
     * @param strICCard
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CLoginUser
     */
    @WebMethod(action = "http://tempuri.org/getUserByICCard")
    @WebResult(name = "getUserByICCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getUserByICCard", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetUserByICCard")
    @ResponseWrapper(localName = "getUserByICCardResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetUserByICCardResponse")
    public CLoginUser getUserByICCard(
        @WebParam(name = "strDomain", targetNamespace = "http://tempuri.org/")
        String strDomain,
        @WebParam(name = "strICCard", targetNamespace = "http://tempuri.org/")
        String strICCard);

    /**
     * 
     * @param strLoginSite
     * @param strUserAccount
     * @param strPassword
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CLoginUser
     */
    @WebMethod(action = "http://tempuri.org/getUserByPW")
    @WebResult(name = "getUserByPWResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getUserByPW", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetUserByPW")
    @ResponseWrapper(localName = "getUserByPWResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetUserByPWResponse")
    public CLoginUser getUserByPW(
        @WebParam(name = "strLoginSite", targetNamespace = "http://tempuri.org/")
        String strLoginSite,
        @WebParam(name = "strUserAccount", targetNamespace = "http://tempuri.org/")
        String strUserAccount,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        String strPassword);

    /**
     * 
     * @param strDomain
     * @param strLeaderAccount
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.ArrayOfCLocation
     */
    @WebMethod(action = "http://tempuri.org/getResponsibleLocationByLeaderUser")
    @WebResult(name = "getResponsibleLocationByLeaderUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getResponsibleLocationByLeaderUser", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetResponsibleLocationByLeaderUser")
    @ResponseWrapper(localName = "getResponsibleLocationByLeaderUserResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetResponsibleLocationByLeaderUserResponse")
    public ArrayOfCLocation getResponsibleLocationByLeaderUser(
        @WebParam(name = "strDomain", targetNamespace = "http://tempuri.org/")
        String strDomain,
        @WebParam(name = "strLeaderAccount", targetNamespace = "http://tempuri.org/")
        String strLeaderAccount);

    /**
     * 
     * @param strDomain
     * @param iUserId
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.ArrayOfCLocation
     */
    @WebMethod(action = "http://tempuri.org/getSourceLocationsByUserId")
    @WebResult(name = "getSourceLocationsByUserIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getSourceLocationsByUserId", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetSourceLocationsByUserId")
    @ResponseWrapper(localName = "getSourceLocationsByUserIdResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetSourceLocationsByUserIdResponse")
    public ArrayOfCLocation getSourceLocationsByUserId(
        @WebParam(name = "strDomain", targetNamespace = "http://tempuri.org/")
        String strDomain,
        @WebParam(name = "iUserId", targetNamespace = "http://tempuri.org/")
        int iUserId);

    /**
     * 
     * @param strDomain
     * @param strSite
     * @param strLoc
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.ArrayOfCLoginUser
     */
    @WebMethod(action = "http://tempuri.org/getUserListByLocation")
    @WebResult(name = "getUserListByLocationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getUserListByLocation", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetUserListByLocation")
    @ResponseWrapper(localName = "getUserListByLocationResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetUserListByLocationResponse")
    public ArrayOfCLoginUser getUserListByLocation(
        @WebParam(name = "strDomain", targetNamespace = "http://tempuri.org/")
        String strDomain,
        @WebParam(name = "strLoc", targetNamespace = "http://tempuri.org/")
        String strLoc,
        @WebParam(name = "strSite", targetNamespace = "http://tempuri.org/")
        String strSite);

    /**
     * 
     * @param strDomain
     * @param strUserAccount
     * @param strCardNo
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://tempuri.org/bindUserICCard")
    @WebResult(name = "bindUserICCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "bindUserICCard", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.BindUserICCard")
    @ResponseWrapper(localName = "bindUserICCardResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.BindUserICCardResponse")
    public boolean bindUserICCard(
        @WebParam(name = "strDomain", targetNamespace = "http://tempuri.org/")
        String strDomain,
        @WebParam(name = "strUserAccount", targetNamespace = "http://tempuri.org/")
        String strUserAccount,
        @WebParam(name = "strCardNo", targetNamespace = "http://tempuri.org/")
        String strCardNo);

    /**
     * 
     * @param loginUser
     * @param scanBBCList
     * @param tranOption
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.ArrayOfCScanBBC
     */
    @WebMethod(operationName = "WebTest", action = "http://tempuri.org/WebTest")
    @WebResult(name = "WebTestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "WebTest", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.WebTest")
    @ResponseWrapper(localName = "WebTestResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.WebTestResponse")
    public ArrayOfCScanBBC webTest(
        @WebParam(name = "loginUser", targetNamespace = "http://tempuri.org/")
        CLoginUser loginUser,
        @WebParam(name = "tranOption", targetNamespace = "http://tempuri.org/")
        CTransferOption tranOption,
        @WebParam(name = "scanBBCList", targetNamespace = "http://tempuri.org/")
        ArrayOfCScanBBC scanBBCList);

    /**
     * 
     * @param strBBC
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CBBC
     */
    @WebMethod(operationName = "GetBBCInfo", action = "http://tempuri.org/GetBBCInfo")
    @WebResult(name = "GetBBCInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBBCInfo", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetBBCInfo")
    @ResponseWrapper(localName = "GetBBCInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetBBCInfoResponse")
    public CBBC getBBCInfo(
        @WebParam(name = "strBBC", targetNamespace = "http://tempuri.org/")
        String strBBC);

    /**
     * 
     * @param strPldNo
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.ArrayOfCBBC
     */
    @WebMethod(operationName = "GetBBCByPLDNo", action = "http://tempuri.org/GetBBCByPLDNo")
    @WebResult(name = "GetBBCByPLDNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBBCByPLDNo", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetBBCByPLDNo")
    @ResponseWrapper(localName = "GetBBCByPLDNoResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetBBCByPLDNoResponse")
    public ArrayOfCBBC getBBCByPLDNo(
        @WebParam(name = "strPldNo", targetNamespace = "http://tempuri.org/")
        String strPldNo);

    /**
     * 
     * @param scanBBC
     * @param loginUser
     * @param tranOption
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CBBCResult
     */
    @WebMethod(operationName = "SingleTransferCheck", action = "http://tempuri.org/SingleTransferCheck")
    @WebResult(name = "SingleTransferCheckResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SingleTransferCheck", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.SingleTransferCheck")
    @ResponseWrapper(localName = "SingleTransferCheckResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.SingleTransferCheckResponse")
    public CBBCResult singleTransferCheck(
        @WebParam(name = "loginUser", targetNamespace = "http://tempuri.org/")
        CLoginUser loginUser,
        @WebParam(name = "tranOption", targetNamespace = "http://tempuri.org/")
        CTransferOption tranOption,
        @WebParam(name = "scanBBC", targetNamespace = "http://tempuri.org/")
        CScanBBC scanBBC);

    /**
     * 
     * @param scanBBC
     * @param loginUser
     * @param scannedBBCList
     * @param tranOption
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CBBCResult
     */
    @WebMethod(operationName = "SingleTransferCheckFIFO", action = "http://tempuri.org/SingleTransferCheckFIFO")
    @WebResult(name = "SingleTransferCheckFIFOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SingleTransferCheckFIFO", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.SingleTransferCheckFIFO")
    @ResponseWrapper(localName = "SingleTransferCheckFIFOResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.SingleTransferCheckFIFOResponse")
    public CBBCResult singleTransferCheckFIFO(
        @WebParam(name = "loginUser", targetNamespace = "http://tempuri.org/")
        CLoginUser loginUser,
        @WebParam(name = "tranOption", targetNamespace = "http://tempuri.org/")
        CTransferOption tranOption,
        @WebParam(name = "scanBBC", targetNamespace = "http://tempuri.org/")
        CScanBBC scanBBC,
        @WebParam(name = "scannedBBCList", targetNamespace = "http://tempuri.org/")
        ArrayOfString scannedBBCList);

    /**
     * 
     * @param loginUser
     * @param scanBBCList
     * @param tranOption
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CBBCResultList
     */
    @WebMethod(operationName = "BatchTransferCheck", action = "http://tempuri.org/BatchTransferCheck")
    @WebResult(name = "BatchTransferCheckResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BatchTransferCheck", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.BatchTransferCheck")
    @ResponseWrapper(localName = "BatchTransferCheckResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.BatchTransferCheckResponse")
    public CBBCResultList batchTransferCheck(
        @WebParam(name = "loginUser", targetNamespace = "http://tempuri.org/")
        CLoginUser loginUser,
        @WebParam(name = "tranOption", targetNamespace = "http://tempuri.org/")
        CTransferOption tranOption,
        @WebParam(name = "scanBBCList", targetNamespace = "http://tempuri.org/")
        ArrayOfCScanBBC scanBBCList);

    /**
     * 
     * @param loginUser
     * @param scannedBBCList
     * @param billNo
     * @param tranOption
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CBBCResultList
     */
    @WebMethod(operationName = "BatchTransferCheckByBillNo", action = "http://tempuri.org/BatchTransferCheckByBillNo")
    @WebResult(name = "BatchTransferCheckByBillNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BatchTransferCheckByBillNo", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.BatchTransferCheckByBillNo")
    @ResponseWrapper(localName = "BatchTransferCheckByBillNoResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.BatchTransferCheckByBillNoResponse")
    public CBBCResultList batchTransferCheckByBillNo(
        @WebParam(name = "loginUser", targetNamespace = "http://tempuri.org/")
        CLoginUser loginUser,
        @WebParam(name = "tranOption", targetNamespace = "http://tempuri.org/")
        CTransferOption tranOption,
        @WebParam(name = "billNo", targetNamespace = "http://tempuri.org/")
        String billNo,
        @WebParam(name = "scannedBBCList", targetNamespace = "http://tempuri.org/")
        ArrayOfString scannedBBCList);

    /**
     * 
     * @param loginUser
     * @param scanBBCList
     * @param tranOption
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CBBCResultList
     */
    @WebMethod(operationName = "SubmitTransfer", action = "http://tempuri.org/SubmitTransfer")
    @WebResult(name = "SubmitTransferResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SubmitTransfer", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.SubmitTransfer")
    @ResponseWrapper(localName = "SubmitTransferResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.SubmitTransferResponse")
    public CBBCResultList submitTransfer(
        @WebParam(name = "loginUser", targetNamespace = "http://tempuri.org/")
        CLoginUser loginUser,
        @WebParam(name = "tranOption", targetNamespace = "http://tempuri.org/")
        CTransferOption tranOption,
        @WebParam(name = "scanBBCList", targetNamespace = "http://tempuri.org/")
        ArrayOfCScanBBC scanBBCList);

    /**
     * 
     * @param scanBBC
     * @param loginUser
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SingleBBCSendWithdraw", action = "http://tempuri.org/SingleBBCSendWithdraw")
    @WebResult(name = "SingleBBCSendWithdrawResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SingleBBCSendWithdraw", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.SingleBBCSendWithdraw")
    @ResponseWrapper(localName = "SingleBBCSendWithdrawResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.SingleBBCSendWithdrawResponse")
    public boolean singleBBCSendWithdraw(
        @WebParam(name = "loginUser", targetNamespace = "http://tempuri.org/")
        CLoginUser loginUser,
        @WebParam(name = "scanBBC", targetNamespace = "http://tempuri.org/")
        CScanBBC scanBBC);

    /**
     * 
     * @param loginUser
     * @param scanBBCList
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "BatchBBCSendWithdraw", action = "http://tempuri.org/BatchBBCSendWithdraw")
    @WebResult(name = "BatchBBCSendWithdrawResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BatchBBCSendWithdraw", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.BatchBBCSendWithdraw")
    @ResponseWrapper(localName = "BatchBBCSendWithdrawResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.BatchBBCSendWithdrawResponse")
    public boolean batchBBCSendWithdraw(
        @WebParam(name = "loginUser", targetNamespace = "http://tempuri.org/")
        CLoginUser loginUser,
        @WebParam(name = "scanBBCList", targetNamespace = "http://tempuri.org/")
        ArrayOfCScanBBC scanBBCList);

    /**
     * 
     * @param loginDomain
     * @param strBBC
     * @param loginUserId
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CBackFlushBBC
     */
    @WebMethod(operationName = "GetBackFlushBBCInfo", action = "http://tempuri.org/GetBackFlushBBCInfo")
    @WebResult(name = "GetBackFlushBBCInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBackFlushBBCInfo", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetBackFlushBBCInfo")
    @ResponseWrapper(localName = "GetBackFlushBBCInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.GetBackFlushBBCInfoResponse")
    public CBackFlushBBC getBackFlushBBCInfo(
        @WebParam(name = "loginDomain", targetNamespace = "http://tempuri.org/")
        String loginDomain,
        @WebParam(name = "loginUserId", targetNamespace = "http://tempuri.org/")
        int loginUserId,
        @WebParam(name = "strBBC", targetNamespace = "http://tempuri.org/")
        String strBBC);

    /**
     * 
     * @param loginDomain
     * @param scanBBCList
     * @param clientIP
     * @param bfOption
     * @param loginUserId
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CBackFlushBBCResult
     */
    @WebMethod(operationName = "BackFlushCheck", action = "http://tempuri.org/BackFlushCheck")
    @WebResult(name = "BackFlushCheckResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BackFlushCheck", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.BackFlushCheck")
    @ResponseWrapper(localName = "BackFlushCheckResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.BackFlushCheckResponse")
    public CBackFlushBBCResult backFlushCheck(
        @WebParam(name = "loginDomain", targetNamespace = "http://tempuri.org/")
        String loginDomain,
        @WebParam(name = "loginUserId", targetNamespace = "http://tempuri.org/")
        int loginUserId,
        @WebParam(name = "clientIP", targetNamespace = "http://tempuri.org/")
        String clientIP,
        @WebParam(name = "bfOption", targetNamespace = "http://tempuri.org/")
        CBackFlushOption bfOption,
        @WebParam(name = "scanBBCList", targetNamespace = "http://tempuri.org/")
        ArrayOfCScanBackFlushBBC scanBBCList);

    /**
     * 
     * @param loginDomain
     * @param scanBBCList
     * @param clientIP
     * @param bfOption
     * @param loginUserId
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.CBackFlushBBCResult
     */
    @WebMethod(operationName = "SubmitBackFlush", action = "http://tempuri.org/SubmitBackFlush")
    @WebResult(name = "SubmitBackFlushResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SubmitBackFlush", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.SubmitBackFlush")
    @ResponseWrapper(localName = "SubmitBackFlushResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.SubmitBackFlushResponse")
    public CBackFlushBBCResult submitBackFlush(
        @WebParam(name = "loginDomain", targetNamespace = "http://tempuri.org/")
        String loginDomain,
        @WebParam(name = "loginUserId", targetNamespace = "http://tempuri.org/")
        int loginUserId,
        @WebParam(name = "clientIP", targetNamespace = "http://tempuri.org/")
        String clientIP,
        @WebParam(name = "bfOption", targetNamespace = "http://tempuri.org/")
        CBackFlushOption bfOption,
        @WebParam(name = "scanBBCList", targetNamespace = "http://tempuri.org/")
        ArrayOfCScanBackFlushBBC scanBBCList);

    /**
     * 
     * @param loginDomain
     * @param strLocation
     * @param arrBBC
     * @param loginUserId
     * @return
     *     returns com.uspring.sdsmesplus.barcode.soap.ArrayOfCBBC
     */
    @WebMethod(operationName = "StocktakeScan", action = "http://tempuri.org/StocktakeScan")
    @WebResult(name = "StocktakeScanResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StocktakeScan", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.StocktakeScan")
    @ResponseWrapper(localName = "StocktakeScanResponse", targetNamespace = "http://tempuri.org/", className = "com.uspring.sdsmesplus.barcode.soap.StocktakeScanResponse")
    public ArrayOfCBBC stocktakeScan(
        @WebParam(name = "loginDomain", targetNamespace = "http://tempuri.org/")
        String loginDomain,
        @WebParam(name = "loginUserId", targetNamespace = "http://tempuri.org/")
        int loginUserId,
        @WebParam(name = "strLocation", targetNamespace = "http://tempuri.org/")
        String strLocation,
        @WebParam(name = "arrBBC", targetNamespace = "http://tempuri.org/")
        ArrayOfString arrBBC);

}
