
package com.uspring.sdsmesplus.barcode.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PDAWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.50.52.152:10005/PDAWebService.wsdl")
public class PDAWebService
    extends Service
{

    private final static URL PDAWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException PDAWEBSERVICE_EXCEPTION;
    private final static QName PDAWEBSERVICE_QNAME = new QName("http://tempuri.org/", "PDAWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.52.152:10005/PDAWebService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PDAWEBSERVICE_WSDL_LOCATION = url;
        PDAWEBSERVICE_EXCEPTION = e;
    }

    public PDAWebService() {
        super(__getWsdlLocation(), PDAWEBSERVICE_QNAME);
    }

    public PDAWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PDAWEBSERVICE_QNAME, features);
    }

    public PDAWebService(URL wsdlLocation) {
        super(wsdlLocation, PDAWEBSERVICE_QNAME);
    }

    public PDAWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PDAWEBSERVICE_QNAME, features);
    }

    public PDAWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PDAWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PDAWebServiceSoap
     */
    @WebEndpoint(name = "PDAWebServiceSoap")
    public PDAWebServiceSoap getPDAWebServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "PDAWebServiceSoap"), PDAWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PDAWebServiceSoap
     */
    @WebEndpoint(name = "PDAWebServiceSoap")
    public PDAWebServiceSoap getPDAWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "PDAWebServiceSoap"), PDAWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PDAWEBSERVICE_EXCEPTION!= null) {
            throw PDAWEBSERVICE_EXCEPTION;
        }
        return PDAWEBSERVICE_WSDL_LOCATION;
    }

}
