
package com.uspring.sdsmesplus.wms.sap.f128;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_MES_GoodIssues_Out", targetNamespace = "urn:mes:GoodIssues")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIMESGoodIssuesOut {


    /**
     * 
     * @param mtGoodIssues
     * @return
     *     returns com.uspring.sdsmesplus.wms.sap.f128.DTGoodIssuesRT
     */
    @WebMethod(operationName = "SI_MES_GoodIssues_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_GoodIssues_RT", targetNamespace = "urn:mes:GoodIssues", partName = "MT_GoodIssues_RT")
    public DTGoodIssuesRT siMESGoodIssuesOut(
        @WebParam(name = "MT_GoodIssues", targetNamespace = "urn:mes:GoodIssues", partName = "MT_GoodIssues")
        DTGoodIssues mtGoodIssues);

}
