
package com.uspring.sdsmesplus.wms.sap.f245;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MES_Unpacking_OutService", targetNamespace = "urn:mes:Unpacking", wsdlLocation = "file:/D:/F245_QAS_SI_MES_Unpacking_OutService.wsdl")
public class SIMESUnpackingOutService
    extends Service
{

    private final static URL SIMESUNPACKINGOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMESUNPACKINGOUTSERVICE_EXCEPTION;
    private final static QName SIMESUNPACKINGOUTSERVICE_QNAME = new QName("urn:mes:Unpacking", "SI_MES_Unpacking_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/F245_QAS_SI_MES_Unpacking_OutService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMESUNPACKINGOUTSERVICE_WSDL_LOCATION = url;
        SIMESUNPACKINGOUTSERVICE_EXCEPTION = e;
    }

    public SIMESUnpackingOutService() {
        super(__getWsdlLocation(), SIMESUNPACKINGOUTSERVICE_QNAME);
    }

    public SIMESUnpackingOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMESUNPACKINGOUTSERVICE_QNAME, features);
    }

    public SIMESUnpackingOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMESUNPACKINGOUTSERVICE_QNAME);
    }

    public SIMESUnpackingOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMESUNPACKINGOUTSERVICE_QNAME, features);
    }

    public SIMESUnpackingOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMESUnpackingOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMESUnpackingOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESUnpackingOut getHTTPPort() {
        return super.getPort(new QName("urn:mes:Unpacking", "HTTP_Port"), SIMESUnpackingOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESUnpackingOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESUnpackingOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:Unpacking", "HTTP_Port"), SIMESUnpackingOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMESUnpackingOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESUnpackingOut getHTTPSPort() {
        return super.getPort(new QName("urn:mes:Unpacking", "HTTPS_Port"), SIMESUnpackingOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESUnpackingOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESUnpackingOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:Unpacking", "HTTPS_Port"), SIMESUnpackingOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMESUNPACKINGOUTSERVICE_EXCEPTION!= null) {
            throw SIMESUNPACKINGOUTSERVICE_EXCEPTION;
        }
        return SIMESUNPACKINGOUTSERVICE_WSDL_LOCATION;
    }

}
