
package com.uspring.sdsmesplus.wms.sap.f261;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MES2EWM_GetHUNumbers_Sync_OutService", targetNamespace = "urn:mes:GetHUNumbers", wsdlLocation = "http://10.50.52.152:10005/F261_QAS_SI_MES2EWM_GetHUNumbers_Sync_OutService.wsdl")
public class SIMES2EWMGetHUNumbersSyncOutService
    extends Service
{

    private final static URL SIMES2EWMGETHUNUMBERSSYNCOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMES2EWMGETHUNUMBERSSYNCOUTSERVICE_EXCEPTION;
    private final static QName SIMES2EWMGETHUNUMBERSSYNCOUTSERVICE_QNAME = new QName("urn:mes:GetHUNumbers", "SI_MES2EWM_GetHUNumbers_Sync_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.52.152:10005/F261_QAS_SI_MES2EWM_GetHUNumbers_Sync_OutService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMES2EWMGETHUNUMBERSSYNCOUTSERVICE_WSDL_LOCATION = url;
        SIMES2EWMGETHUNUMBERSSYNCOUTSERVICE_EXCEPTION = e;
    }

    public SIMES2EWMGetHUNumbersSyncOutService() {
        super(__getWsdlLocation(), SIMES2EWMGETHUNUMBERSSYNCOUTSERVICE_QNAME);
    }

    public SIMES2EWMGetHUNumbersSyncOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMES2EWMGETHUNUMBERSSYNCOUTSERVICE_QNAME, features);
    }

    public SIMES2EWMGetHUNumbersSyncOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMES2EWMGETHUNUMBERSSYNCOUTSERVICE_QNAME);
    }

    public SIMES2EWMGetHUNumbersSyncOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMES2EWMGETHUNUMBERSSYNCOUTSERVICE_QNAME, features);
    }

    public SIMES2EWMGetHUNumbersSyncOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMES2EWMGetHUNumbersSyncOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMES2EWMGetHUNumbersSyncOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMES2EWMGetHUNumbersSyncOut getHTTPPort() {
        return super.getPort(new QName("urn:mes:GetHUNumbers", "HTTP_Port"), SIMES2EWMGetHUNumbersSyncOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMES2EWMGetHUNumbersSyncOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMES2EWMGetHUNumbersSyncOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:GetHUNumbers", "HTTP_Port"), SIMES2EWMGetHUNumbersSyncOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMES2EWMGetHUNumbersSyncOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMES2EWMGetHUNumbersSyncOut getHTTPSPort() {
        return super.getPort(new QName("urn:mes:GetHUNumbers", "HTTPS_Port"), SIMES2EWMGetHUNumbersSyncOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMES2EWMGetHUNumbersSyncOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMES2EWMGetHUNumbersSyncOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:GetHUNumbers", "HTTPS_Port"), SIMES2EWMGetHUNumbersSyncOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMES2EWMGETHUNUMBERSSYNCOUTSERVICE_EXCEPTION!= null) {
            throw SIMES2EWMGETHUNUMBERSSYNCOUTSERVICE_EXCEPTION;
        }
        return SIMES2EWMGETHUNUMBERSSYNCOUTSERVICE_WSDL_LOCATION;
    }

}
