
package com.uspring.sdsmesplus.wms.sap.f261;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_MES2EWM_GetHUNumbers_Sync_Out", targetNamespace = "urn:mes:GetHUNumbers")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIMES2EWMGetHUNumbersSyncOut {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.uspring.sdsmesplus.wms.sap.f261.ZEWMRFCGENERATEHUNUMBERResponse
     */
    @WebMethod(operationName = "SI_GetHUNumbers_Sync_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ZEWMRFC_GENERATE_HU_NUMBER.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    public ZEWMRFCGENERATEHUNUMBERResponse siGetHUNumbersSyncOut(
        @WebParam(name = "ZEWMRFC_GENERATE_HU_NUMBER", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
        ZEWMRFCGENERATEHUNUMBER parameters);

}
