
package com.uspring.sdsmesplus.wms.sap.f132;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_MES_ClearLineReport_Out", targetNamespace = "urn:mes:ClearLineReport")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIMESClearLineReportOut {


    /**
     * 
     * @param mtEWMIQX
     * @return
     *     returns com.uspring.sdsmesplus.wms.sap.f132.DTEWMIQXRT
     */
    @WebMethod(operationName = "SI_MES_ClearLineReport_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_EWMI_QX_RT", targetNamespace = "urn:mes:ClearLineReport", partName = "MT_EWMI_QX_RT")
    public DTEWMIQXRT siMESClearLineReportOut(
        @WebParam(name = "MT_EWMI_QX", targetNamespace = "urn:mes:ClearLineReport", partName = "MT_EWMI_QX")
        DTEWMIQX mtEWMIQX);

}
