
package com.uspring.sdsmesplus.wms.sap.f132;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MES_ClearLineReport_OutService", targetNamespace = "urn:mes:ClearLineReport", wsdlLocation = "http://10.50.52.152:10005/F132_QAS_SI_MES_ClearLineReport_OutService.wsdl")
public class SIMESClearLineReportOutService
    extends Service
{

    private final static URL SIMESCLEARLINEREPORTOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMESCLEARLINEREPORTOUTSERVICE_EXCEPTION;
    private final static QName SIMESCLEARLINEREPORTOUTSERVICE_QNAME = new QName("urn:mes:ClearLineReport", "SI_MES_ClearLineReport_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.52.152:10005/F132_QAS_SI_MES_ClearLineReport_OutService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMESCLEARLINEREPORTOUTSERVICE_WSDL_LOCATION = url;
        SIMESCLEARLINEREPORTOUTSERVICE_EXCEPTION = e;
    }

    public SIMESClearLineReportOutService() {
        super(__getWsdlLocation(), SIMESCLEARLINEREPORTOUTSERVICE_QNAME);
    }

    public SIMESClearLineReportOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMESCLEARLINEREPORTOUTSERVICE_QNAME, features);
    }

    public SIMESClearLineReportOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMESCLEARLINEREPORTOUTSERVICE_QNAME);
    }

    public SIMESClearLineReportOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMESCLEARLINEREPORTOUTSERVICE_QNAME, features);
    }

    public SIMESClearLineReportOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMESClearLineReportOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMESClearLineReportOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESClearLineReportOut getHTTPPort() {
        return super.getPort(new QName("urn:mes:ClearLineReport", "HTTP_Port"), SIMESClearLineReportOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESClearLineReportOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESClearLineReportOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:ClearLineReport", "HTTP_Port"), SIMESClearLineReportOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMESClearLineReportOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESClearLineReportOut getHTTPSPort() {
        return super.getPort(new QName("urn:mes:ClearLineReport", "HTTPS_Port"), SIMESClearLineReportOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESClearLineReportOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESClearLineReportOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:ClearLineReport", "HTTPS_Port"), SIMESClearLineReportOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMESCLEARLINEREPORTOUTSERVICE_EXCEPTION!= null) {
            throw SIMESCLEARLINEREPORTOUTSERVICE_EXCEPTION;
        }
        return SIMESCLEARLINEREPORTOUTSERVICE_WSDL_LOCATION;
    }

}
