
package com.uspring.sdsmesplus.wms.sap.f133;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_MES_GetHuDetails_Out", targetNamespace = "urn:mes:f133:GetHuDetails")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIMESGetHuDetailsOut {


    /**
     * 
     * @param mtGetHuData
     * @return
     *     returns com.uspring.sdsmesplus.wms.sap.f133.DTGetHuDataRT
     */
    @WebMethod(operationName = "SI_MES_GetHuDetails_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_GetHuData_RT", targetNamespace = "urn:mes:f133:GetHuDetails", partName = "MT_GetHuData_RT")
    public DTGetHuDataRT siMESGetHuDetailsOut(
        @WebParam(name = "MT_GetHuData", targetNamespace = "urn:mes:f133:GetHuDetails", partName = "MT_GetHuData")
        DTGetHuData mtGetHuData);

}
