
package com.uspring.sdsmesplus.wms.sap.f133;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MES_GetHuDetails_OutService", targetNamespace = "urn:mes:f133:GetHuDetails", wsdlLocation = "http://10.50.52.152:10005/F133_QAS_SI_MES_GetHuDetails_OutService.wsdl")
public class SIMESGetHuDetailsOutService
    extends Service
{

    private final static URL SIMESGETHUDETAILSOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMESGETHUDETAILSOUTSERVICE_EXCEPTION;
    private final static QName SIMESGETHUDETAILSOUTSERVICE_QNAME = new QName("urn:mes:f133:GetHuDetails", "SI_MES_GetHuDetails_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.52.152:10005/F133_QAS_SI_MES_GetHuDetails_OutService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMESGETHUDETAILSOUTSERVICE_WSDL_LOCATION = url;
        SIMESGETHUDETAILSOUTSERVICE_EXCEPTION = e;
    }

    public SIMESGetHuDetailsOutService() {
        super(__getWsdlLocation(), SIMESGETHUDETAILSOUTSERVICE_QNAME);
    }

    public SIMESGetHuDetailsOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMESGETHUDETAILSOUTSERVICE_QNAME, features);
    }

    public SIMESGetHuDetailsOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMESGETHUDETAILSOUTSERVICE_QNAME);
    }

    public SIMESGetHuDetailsOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMESGETHUDETAILSOUTSERVICE_QNAME, features);
    }

    public SIMESGetHuDetailsOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMESGetHuDetailsOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMESGetHuDetailsOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESGetHuDetailsOut getHTTPPort() {
        return super.getPort(new QName("urn:mes:f133:GetHuDetails", "HTTP_Port"), SIMESGetHuDetailsOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESGetHuDetailsOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESGetHuDetailsOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:f133:GetHuDetails", "HTTP_Port"), SIMESGetHuDetailsOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMESGetHuDetailsOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESGetHuDetailsOut getHTTPSPort() {
        return super.getPort(new QName("urn:mes:f133:GetHuDetails", "HTTPS_Port"), SIMESGetHuDetailsOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESGetHuDetailsOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESGetHuDetailsOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:f133:GetHuDetails", "HTTPS_Port"), SIMESGetHuDetailsOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMESGETHUDETAILSOUTSERVICE_EXCEPTION!= null) {
            throw SIMESGETHUDETAILSOUTSERVICE_EXCEPTION;
        }
        return SIMESGETHUDETAILSOUTSERVICE_WSDL_LOCATION;
    }

}
