
package com.uspring.sdsmesplus.wms.sap.f241;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_MES_MoveStock_OutService", targetNamespace = "urn:mes:MoveStock", wsdlLocation = "http://10.50.52.152:10005/F241_QAS_SI_MES_MoveStock_OutService.wsdl")
public class SIMESMoveStockOutService
    extends Service
{

    private final static URL SIMESMOVESTOCKOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMESMOVESTOCKOUTSERVICE_EXCEPTION;
    private final static QName SIMESMOVESTOCKOUTSERVICE_QNAME = new QName("urn:mes:MoveStock", "SI_MES_MoveStock_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.52.152:10005/F241_QAS_SI_MES_MoveStock_OutService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMESMOVESTOCKOUTSERVICE_WSDL_LOCATION = url;
        SIMESMOVESTOCKOUTSERVICE_EXCEPTION = e;
    }

    public SIMESMoveStockOutService() {
        super(__getWsdlLocation(), SIMESMOVESTOCKOUTSERVICE_QNAME);
    }

    public SIMESMoveStockOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMESMOVESTOCKOUTSERVICE_QNAME, features);
    }

    public SIMESMoveStockOutService(URL wsdlLocation) {
        super(wsdlLocation, SIMESMOVESTOCKOUTSERVICE_QNAME);
    }

    public SIMESMoveStockOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMESMOVESTOCKOUTSERVICE_QNAME, features);
    }

    public SIMESMoveStockOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMESMoveStockOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMESMoveStockOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESMoveStockOut getHTTPPort() {
        return super.getPort(new QName("urn:mes:MoveStock", "HTTP_Port"), SIMESMoveStockOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESMoveStockOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIMESMoveStockOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:MoveStock", "HTTP_Port"), SIMESMoveStockOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIMESMoveStockOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESMoveStockOut getHTTPSPort() {
        return super.getPort(new QName("urn:mes:MoveStock", "HTTPS_Port"), SIMESMoveStockOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMESMoveStockOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIMESMoveStockOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:mes:MoveStock", "HTTPS_Port"), SIMESMoveStockOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMESMOVESTOCKOUTSERVICE_EXCEPTION!= null) {
            throw SIMESMOVESTOCKOUTSERVICE_EXCEPTION;
        }
        return SIMESMOVESTOCKOUTSERVICE_WSDL_LOCATION;
    }

}
