
package com.uspring.sdsmesplus.wms.sap.f241;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_MES_MoveStock_Out", targetNamespace = "urn:mes:MoveStock")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIMESMoveStockOut {


    /**
     * 
     * @param mtMoveStockReq
     * @return
     *     returns com.uspring.sdsmesplus.wms.sap.f241.DTMoveStockRet
     */
    @WebMethod(operationName = "SI_MES_MoveStock_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_MoveStock_Ret", targetNamespace = "urn:mes:MoveStock", partName = "MT_MoveStock_Ret")
    public DTMoveStockRet siMESMoveStockOut(
        @WebParam(name = "MT_MoveStock_Req", targetNamespace = "urn:mes:MoveStock", partName = "MT_MoveStock_Req")
        DTMoveStockReq mtMoveStockReq);

}
